-- Siembra inicial del organizador. **Retirada.**
--
-- Este archivo creaba `sembrar_organizador()`, un arranque de una sola vez que
-- daba de alta los espacios, los proyectos y sus tareas con quien la llamara
-- como dueño. `0009_retirar_semilla.sql` la elimina de la base, por las razones
-- que ahí se explican.
--
-- Su contenido también se retira del repositorio. No era esquema: era el
-- volcado de los datos reales del dueño, con nombres de socios, de clientes y
-- de sus proyectos, además de hallazgos de seguridad de un sistema en
-- producción. Todo eso vive en la base, donde las políticas por fila deciden
-- quién lo alcanza; en un archivo del repositorio no lo decide nadie.
--
-- La numeración se conserva para que los archivos sigan casando con el orden en
-- que se aplicaron las migraciones.
--
-- Nada que ejecutar.
